Add repository-slug/
ia-toki/toki-style-guides pull request #1
Opened 2017-06-20 01:24 UTC by jonathanirvings

2017-06-28 10:00 UTC, fushar requested changes
Secara umum, sudah bagus! Satu komentar terakhir yang berlaku umum: sebaiknya untuk setiap format, selalu ada minimal satu contoh. Misalnya, bagian yang "diawali dengan username-TESTING", beri contoh misalnya `dengklek-TESTING-python4-stress-test`.

2017-06-28 10:00 UTC, fushar commented on repository-slug/README.md
> +[TLX Repository Gate](https://repository.ia-toki.org/) adalah tempat untuk meletakan soal-soal yang digunakan di TLX, baik [TLX Training Gate](https://training.ia-toki.org/) maupun [TLX Competition G
- Statistik banyaknya kontes/soal/dll sepertinya di luar cakupan dokumen ini; `ratusan`/`ribuan` sudah cukup.
- Tidak perlu menyebutkan kontes luar TOKI secara spesifik (BL).

2017-06-28 10:00 UTC, fushar commented on repository-slug/README.md
> +Sebagai contoh, `toki-oc-mei-17-teman-terbaik`, `osn-informatika-2012-sungai-biner`, `gemastik-2016-final-e-irigasi` adalah slug yang baik.
Apakah penulisan `17` alih-alih `2017`, disengaja di sini?

2017-06-28 10:00 UTC, fushar commented on repository-slug/README.md
> +Jika soal bukan merupakan soal kontes dan juga tidak digunakan untuk TLX Training Gate, maka slug soal harus diawali dengan `<username TLX Anda>`. Jika username TLX Anda memiliki karakter yang bukan
Wogh, ide bagus, setuju!

2017-06-28 10:00 UTC, fushar commented on repository-slug/README.md
> +Jika Anda membuat soal yang digunakan untuk menguji atau mencoba-coba sistem TLX Repository Gate, maka slug soal harus diawali dengan `<username TLX Anda>-TESTING`. Diharap untuk meminimalisasi banya
👍

2017-06-28 10:00 UTC, fushar commented on repository-slug/README.md
> +Dalam kasus ini, slug soal modifikasi ini harus mengikuti format dibawah ini
Bagaimana kalau ada 2 soal yang merupakan modifikasi dari suatu soal? Apakah diakhiri dengan `modified-2` ?

2017-06-28 10:00 UTC, fushar commented on repository-slug/README.md
> +Sebagai contoh, `toki-oc-mei-17-teman-terbaik`, `osn-informatika-2012-sungai-biner`, `gemastik-2016-final-e-irigasi` adalah slug yang baik.
Bagaimana pendapat lu tentang alias soal (A B C D dll) dalam slug, seperti pada contoh `gemastik-2016-final-e-irigasi`? Apakah mau dibakukan, atau opsional saja? Misalnya, segera setelah alias soal ditentukan pada suatu kontes, semua slug harus langsung diganti dengan menyertakan aliasnya.

2017-06-28 10:00 UTC, fushar commented on repository-slug/README.md
> +## Soal Training
Bagian ini sebaiknya dihapus, dan nantinya slug-slugnya diperbaiki secara internal.

2017-06-29 02:10 UTC, jonathanirvings commented on repository-slug/README.md
> +[TLX Repository Gate](https://repository.ia-toki.org/) adalah tempat untuk meletakan soal-soal yang digunakan di TLX, baik [TLX Training Gate](https://training.ia-toki.org/) maupun [TLX Competition G
Done

2017-06-29 02:12 UTC, jonathanirvings commented on repository-slug/README.md
> +Sebagai contoh, `toki-oc-mei-17-teman-terbaik`, `osn-informatika-2012-sungai-biner`, `gemastik-2016-final-e-irigasi` adalah slug yang baik.
Hmm contoh slug ini adalah contoh slug yang sekarang beneran ada di TLX Repository Gate sih. Sayangnya sekarang format tahun itu tidak seragam. Yang `toki-oc-mei-17-teman-terbaik` saya ganti dengan contoh yang lebih baik saja. Done

2017-06-29 02:13 UTC, jonathanirvings commented on repository-slug/README.md
> +Sebagai contoh, `toki-oc-mei-17-teman-terbaik`, `osn-informatika-2012-sungai-biner`, `gemastik-2016-final-e-irigasi` adalah slug yang baik.
Hmm menurut saya opsional saja sih. Asalkan walaupun tanpa alias soal, slug soal masih menentukan secara unik soal yang mana.

2017-06-29 02:14 UTC, jonathanirvings commented on repository-slug/README.md
> +Dalam kasus ini, slug soal modifikasi ini harus mengikuti format dibawah ini
Nah ini pertanyaan bagus, karena mengakhiri dengan `modified-2`, kita belum menyelesaikan masalah karena mungkin saja soal modifikasi yang pertama dan modifikasi yang kedua dibuat oleh orang yang berbeda dan independen (kedua orang sama sekali tidak tahu bahwa orang lainnya juga melakukan modifikasi). Sampai sekarang, saya juga belum tahu solusi yang paling baik untuk masalah ini. Apakah ada saran?

2017-06-29 02:15 UTC, jonathanirvings commented on repository-slug/README.md
> +## Soal Training
Done

2017-06-29 02:30 UTC, jonathanirvings commented
@fushar all done, please check :)

2017-06-30 07:13 UTC, fushar commented on repository-slug/README.md
> +Dalam kasus ini, slug soal modifikasi ini harus mengikuti format dibawah ini
`-modified-2` aja harusnya aman, soalnya kalau ada 2 orang yang melakukan modifikasi, meskipun independen, yang terakhir bakal gak bisa pakai `-modified` karena udah dipakai oleh yang pertama. (Jadi dia tinggal increment counternya.)

2017-06-30 07:17 UTC, fushar commented on repository-slug/README.md
> +Sebagai contoh, `toki-oc-mei-17-teman-terbaik`, `osn-informatika-2012-sungai-biner`, `gemastik-2016-final-e-irigasi` adalah slug yang baik.
Oke sip, no further action berarti.

2017-06-30 07:23 UTC, jonathanirvings commented on repository-slug/README.md
> +Dalam kasus ini, slug soal modifikasi ini harus mengikuti format dibawah ini
Oh okay then. Done

2017-06-30 07:23 UTC, fushar commented on repository-slug/README.md
> +[TLX Repository Gate](https://repository.ia-toki.org/) adalah tempat untuk meletakan soal-soal yang digunakan di TLX, baik [TLX Training Gate](https://training.ia-toki.org/) maupun [TLX Competition G
Saya agak anti mencantumkan tahun/tanggal/jumlah spesifik di sebuah dokumen style guide, karena seolah-olah maintainer harus terus melakukan update pada statistik ini seiring berjalannya waktu.

Meralat pernyataan saya sebelumnya, bagaimana kalau semua occurrences of 200, 1.000 etc diganti dengan `banyak sekali` ? Jumlah soal tidak terlalu penting; karena yang ditekankan adalah "banyak sekali soal sedemikian sehingga penamaan slug menjadi sangat penting".

2017-06-30 07:24 UTC, fushar reviewed
Done review part 2.

2017-06-30 07:26 UTC, jonathanirvings commented on repository-slug/README.md
> +[TLX Repository Gate](https://repository.ia-toki.org/) adalah tempat untuk meletakan soal-soal yang digunakan di TLX, baik [TLX Training Gate](https://training.ia-toki.org/) maupun [TLX Competition G
Done

2017-06-30 07:30 UTC, fushar approved these changes

2017-06-30 08:08 UTC, merged